export const SELECT_RADIO = 'SELECT_RADIO';
export const SELECT_P2P_RADIO = 'SELECT_P2P_RADIO';

export const MODAL_WINDOW_UNLOCKED = 'MODAL_WINDOW_UNLOCKED';
export const MAIN_PAGE_FETCH_DATA = 'MAIN_PAGE_FETCH_DATA';
